name: Deploy Ansible to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Set up Python & install Ansible + boto3
      run: |
        pip install --upgrade pip
        pip install ansible boto3 botocore
        ansible-galaxy collection install amazon.aws

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create Vault pass
      run: |
        echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ./vault_pass.txt

    - name: Debug inventory output
      run: |
        ansible-inventory -i inventories/dev/hosts.aws_ec2.yml --list --private-key ~/.ssh/id_ed25519

    - name: Run Ansible playbook
      run: |
        ansible-playbook site.yml -i inventories/dev/hosts.aws_ec2.yml --private-key ~/.ssh/id_ed25519
